spring.application.name=blogger-box-backend

server.port=8080

spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.yqyijpnvljjfbfhxdbnf
spring.datasource.password=Yassou03ch83de!+
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update



